image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci
  IMAGE_NAME: aghilas88/demo-cicd

stages:
  - build
  - package
  - deploy

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn package -B -DskipTests"
  artifacts:
    paths:
      - target/*.jar

docker-build:
  stage: package
  script:
    - docker build -t $IMAGE_NAME .
    - docker login -u $REGISTRY_USER -p "$REGISTRY_PASSWORD"
    - docker push $IMAGE_NAME

k8s-deploy:
  image: google/cloud-sdk
  stage: deploy
  script:
    - echo "$GOOGLE_KEY" > key.json
    - gcloud auth activate-service-account --key-file key.json
    - gcloud config set compute/zone europe-west1-b
    - gcloud config set project fluent-tea-263013
    - gcloud container clusters get-credentials demo-cicd
    - kubectl create secret docker-registry hub.docker.credentials --docker-server=https://index.docker.io/v1/ --docker-username=$REGISTRY_USER --docker-password=$REGISTRY_PASSWORD --docker-email=$DOCKER_EMAIL
    - kubectl apply -f deployment.yml
    - kubectl delete secret hub.docker.credentials
    #- kubectl expose deployment demo-cicd --type=LoadBalancer --port 80 --target-port 9090