apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo-cicd
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: demo-cicd
    spec:
      containers:
        - name: demo-cicd
          image: aghilas88/demo-cicd
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
      imagePullSecrets:
        - name: hub.docker.credentials
